stacking-blocks:
  - DIAMOND_BLOCK
  - EMERALD_BLOCK
  - GOLD_BLOCK
  - REDSTONE_BLOCK
  - LAPIS_BLOCK
  - IRON_BLOCK
  - COAL_BLOCK
sneaking-place: ANY
#ANY to place a block but don't make a stacker, HAND to place all blocks in hand of player
sneaking-break: 64
#ALL to break all block on sneaking, ANY to canel the action or write a number to set the number of blok to break